addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC13")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.2")
//addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.3.0")
addSbtPlugin("com.eed3si9n" % "sbt-appengine" % "0.8.0")
//addSbtPlugin("org.skinny-framework" % "sbt-servlet-plugin" % "2.2.3")
